# Generated by Django 4.0.5 on 2022-07-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('취업', '취업'), ('창업', '창업'), ('진학', '진학'), ('기타', '기타')], default='취업', max_length=10),
        ),
    ]
